name: Trigger auto deployment for fastapi-inventory-app

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ main ]
    paths:
    - '**'
    - '.github/workflows/fastapi-inventory-app-AutoDeployTrigger-c21a44e2-1814-4adf-92d2-850f1842e814.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.FASTAPIINVENTORYAPP_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.FASTAPIINVENTORYAPP_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.FASTAPIINVENTORYAPP_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}
          _dockerfilePathKey_: _dockerfilePath_
          _targetLabelKey_: _targetLabel_
          registryUrl: acrfastapiinventory.azurecr.io
          registryUsername: ${{ secrets.FASTAPIINVENTORYAPP_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.FASTAPIINVENTORYAPP_REGISTRY_PASSWORD }}
          containerAppName: fastapi-inventory-app
          resourceGroup: rg-fastapi-inventory
          imageToBuild: acrfastapiinventory.azurecr.io/fastapi-inventory-app:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


